---

- include_tasks: map.yml

- name: install
  package:
    name: '{{ krb5.packages }}'
    state: present

- name: configure krb5
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644

- include_tasks: server.yml
  when: krb5.is_server | bool
