---

- name: load variables
  include_vars:
    file: "{{ map }}.yml"
    name: "{{ map }}"
  loop:
    - default
    - osfamilymap
    - distributionmap
    - fingerprintmap
  loop_control:
    loop_var: map

- name: compute fingerprint
  set_fact:
    ansible_fingerprint: "{{ ansible_distribution+(ansible_distribution_major_version != 'NA') | ternary(ansible_distribution_major_version, '') }}"

- name: compute configuration
  set_fact:
    krb5: "{{ default.krb5 | default({}) | combine(
      osfamilymap[ansible_os_family].krb5 is defined | ternary(osfamilymap[ansible_os_family].krb5, {}),
      distributionmap[ansible_distribution].krb5 is defined | ternary(distributionmap[ansible_distribution].krb5, {}),
      fingerprintmap[ansible_fingerprint].krb5 is defined | ternary(fingerprintmap[ansible_fingerprint].krb5, {}),
      krb5 | default({}),
      recursive=True
      ) }}"
